"use strict";

exports.plugins = new Set([
	'check-es2015-constants',
	'external-helpers',
	'syntax-async-functions',
	'syntax-async-generators',
	'syntax-class-constructor-call',
	'syntax-class-properties',
	'syntax-decorators',
	'syntax-do-expressions',
	'syntax-exponentiation-operator',
	'syntax-export-extensions',
	'syntax-flow',
	'syntax-function-bind',
	'syntax-function-sent',
	'syntax-jsx',
	'syntax-object-rest-spread',
	'syntax-trailing-function-commas',
	'transform-async-functions',
	'transform-async-to-generator',
	'transform-async-to-module-method',
	'transform-class-constructor-call',
	'transform-class-properties',
	'transform-decorators',
	'transform-do-expressions',
	'transform-es2015-arrow-functions',
	'transform-es2015-block-scoped-functions',
	'transform-es2015-block-scoping',
	'transform-es2015-classes',
	'transform-es2015-computed-properties',
	'transform-es2015-destructuring',
	'transform-es2015-duplicate-keys',
	'transform-es2015-for-of',
	'transform-es2015-function-name',
	'transform-es2015-instanceof',
	'transform-es2015-literals',
	'transform-es2015-modules-amd',
	'transform-es2015-modules-commonjs',
	'transform-es2015-modules-systemjs',
	'transform-es2015-modules-umd',
	'transform-es2015-object-super',
	'transform-es2015-parameters',
	'transform-es2015-shorthand-properties',
	'transform-es2015-spread',
	'transform-es2015-sticky-regex',
	'transform-es2015-template-literals',
	'transform-es2015-typeof-symbol',
	'transform-es2015-unicode-regex',
	'transform-es3-member-expression-literals',
	'transform-es3-property-literals',
	'transform-es5-property-mutators',
	'transform-eval',
	'transform-exponentiation-operator',
	'transform-export-extensions',
	'transform-flow-comments',
	'transform-flow-strip-types',
	'transform-function-bind',
	'transform-inline-environment-variables',
	'transform-jscript',
	'transform-member-expression-literals',
	'transform-merge-sibling-variables',
	'transform-minify-booleans',
	'transform-node-env-inline',
	'transform-object-assign',
	'transform-object-rest-spread',
	'transform-object-set-prototype-of-to-assign',
	'transform-property-literals',
	'transform-proto-to-assign',
	'transform-react-constant-elements',
	'transform-react-display-name',
	'transform-react-inline-elements',
	'transform-react-jsx-compat',
	'transform-react-jsx-source',
	'transform-react-jsx',
	'transform-regenerator',
	'transform-remove-console',
	'transform-remove-debugger',
	'transform-runtime',
	'transform-simplify-comparison-operators',
	'transform-strict-mode',
	'transform-undefined-to-void',
	'undeclared-variables-check',
	// 3rd party
	'mjsx',
	'transform-symbol-member',
	'lodash',
	'inferno',
]);

exports.presets = new Map([
	['react', [
	'syntax-flow',
	'syntax-jsx',
	'transform-flow-strip-types',
	'transform-react-jsx',
	'transform-react-display-name',
	]],

	// https://github.com/facebook/react-native/tree/master/babel-preset
	['react-native', [
	'syntax-async-functions',
	'syntax-class-properties',
	'syntax-trailing-function-commas',
	'transform-class-properties',
	'transform-es2015-arrow-functions',
	'transform-es2015-block-scoping',
	'transform-es2015-classes',
	'transform-es2015-computed-properties',
	'check-es2015-constants', // n.b. was the deprecated transform-es2015-constants
	'transform-es2015-destructuring',
	['transform-es2015-modules-commonjs', { strict: false, allowTopLevelThis: true }],
	'transform-es2015-parameters',
	'transform-es2015-shorthand-properties',
	'transform-es2015-spread',
	'transform-es2015-template-literals',
	'transform-flow-strip-types',
	'transform-object-assign',
	'transform-object-rest-spread',
	'transform-react-display-name',
	'transform-react-jsx',
	'transform-regenerator',
	['transform-es2015-for-of', { loose: true }],
	'transform-symbol-member', // part of --preset-react-native
	]],

	['es2015', [
	'transform-es2015-template-literals',
	'transform-es2015-literals',
	'transform-es2015-function-name',
	'transform-es2015-arrow-functions',
	'transform-es2015-block-scoped-functions',
	'transform-es2015-classes',
	'transform-es2015-object-super',
	'transform-es2015-shorthand-properties',
	'transform-es2015-duplicate-keys',
	'transform-es2015-computed-properties',
	'transform-es2015-for-of',
	'transform-es2015-sticky-regex',
	'transform-es2015-unicode-regex',
	'check-es2015-constants',
	'transform-es2015-spread',
	'transform-es2015-parameters',
	'transform-es2015-destructuring',
	'transform-es2015-block-scoping',
	'transform-es2015-typeof-symbol',
	'transform-es2015-modules-commonjs',
	['transform-regenerator', { async: false, asyncGenerators: false }],
	]],

	// as above but add helpers, remove common-js
	['es2015-rollup', [
	'transform-es2015-template-literals',
	'transform-es2015-literals',
	'transform-es2015-function-name',
	'transform-es2015-arrow-functions',
	'transform-es2015-block-scoped-functions',
	'transform-es2015-classes',
	'transform-es2015-object-super',
	'transform-es2015-shorthand-properties',
	'transform-es2015-duplicate-keys',
	'transform-es2015-computed-properties',
	'transform-es2015-for-of',
	'transform-es2015-sticky-regex',
	'transform-es2015-unicode-regex',
	'check-es2015-constants',
	'transform-es2015-spread',
	'transform-es2015-parameters',
	'transform-es2015-destructuring',
	'transform-es2015-block-scoping',
	'transform-es2015-typeof-symbol',
	['transform-regenerator', { async: false, asyncGenerators: false }],
	'external-helpers'
	]],

	['stage-3', [
	'transform-async-to-generator',
	'transform-exponentiation-operator',
	]],

	['stage-2', [
	'transform-async-to-generator',
	'transform-exponentiation-operator',

	'syntax-trailing-function-commas',
	'transform-object-rest-spread',
	]],

	['stage-1', [
	'transform-async-to-generator',
	'transform-exponentiation-operator',

	'syntax-trailing-function-commas',
	'transform-object-rest-spread',

	'transform-class-constructor-call',
	'transform-class-properties',
	'transform-decorators',
	'transform-export-extensions',
	]],

	['stage-0', [
	'transform-async-to-generator',
	'transform-exponentiation-operator',

	'syntax-trailing-function-commas',
	'transform-object-rest-spread',

	'transform-class-constructor-call',
	'transform-class-properties',
	'transform-decorators',
	'transform-export-extensions',

	'transform-do-expressions',
	'transform-function-bind',
	]],
]);

function _(o) {
	var x = Object.keys(o).map(function(k){
		return [k, o[k]];
	});

	return new Map(x)
}

exports.config = new Map([
	['transform-async-to-module-method', {module: String, method: String}],
	['transform-es2015-arrow-functions', {spec: Boolean}],
	['transform-es2015-classes', {loose: Boolean}],
	['transform-es2015-computed-properties', {loose: Boolean}],
	['transform-es2015-for-of', {loose: Boolean}],
	['transform-es2015-modules-commonjs', {allowTopLevelThis: Boolean}],
	['transform-es2015-modules-umd', {globals: Object}], // not currently supported...
	['transform-es2015-spread', {loose: Boolean}],
	['transform-es2015-template-literals', {loose: Boolean, spec: Boolean}],
	['transform-react-jsx', {pragma: String}],
	['transform-regenerator', {asyncGenerators: Boolean, generators: Boolean, async: Boolean}],
	['transform-runtime', {regenerator: Boolean, polyfill: Boolean}],
	['transform-strict-mode', {strict: Boolean}],
	['lodash', {id: String, cwd: String}],
]);
